version: "3"
services:
  db:
    image: "postgres"
    container_name: "rps-db"
    environment:
      POSTGRES_PASSWORD: 'postgres'
    expose:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  server:
    build: RPS
    container_name: "RPS-server"
    entrypoint: ./entrypoint.sh
    depends_on:
      - "db"
      - "redis"
    environment:
      - "PYTHONUNBUFFERED=1"
      - "DB_HOST=rps-db"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
    command: poetry run gunicorn --workers=4 -b 0.0.0.0:8000 RPS.wsgi:application --access-logfile -
    ports:
      - "8000:8000"
    expose:
      - "8000"
volumes:
  database_data:
    driver: local
