# Generated by Django 4.1.3 on 2022-11-13 17:50

from django.db import migrations, models
import games.enums


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('PAUSED', 'Paused')], default=games.enums.GameStatus['PENDING'], max_length=255),
        ),
    ]
