# Generated by Django 4.1.3 on 2022-11-13 18:08

from django.db import migrations, models
import games.enums


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('PENDING', 0), ('STARTED', 1), ('PAUSED', 2)], default=games.enums.GameStatus['PENDING'], max_length=255),
        ),
    ]
