# Generated by Django 4.1.3 on 2022-11-14 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_player_score_player_draws_player_hand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turn', to='games.game'),
        ),
    ]
